FROM python:3.9-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Add source location source
WORKDIR /opt/dagster

COPY source/requirements.txt /opt/dagster/requirements.txt

RUN mkdir -p /opt/dagster/dagster_home /opt/dagster/app && \
    python -m pip install --default-timeout=100 --upgrade pip && \
    pip install --default-timeout=100 dagit dagster-postgres && \
    pip install --no-cache-dir --default-timeout=100 --upgrade -r /opt/dagster/requirements.txt

ADD source /opt/dagster/app/
# Set $DAGSTER_HOME and copy dagster.yaml and workspace.yaml there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY source/dagster.yaml /opt/dagster/dagster_home/

WORKDIR $DAGSTER_HOME

EXPOSE 3000

ENTRYPOINT ["dagster-daemon", "run", "-w", "/opt/dagster/app/dagster/dagster_workspace.yaml"]